namespace BattleChess.Entity
{
    public enum ChampionId
    {
        None = -1,
        HumanBard = 0,
        HumanBartender = 1,
        HumanDoctor = 2,
        HumanJester = 3,
        HumanKing = 4,
        HumanKnightA = 5,
        HumanKnightB = 6,
        HumanKnightC = 7,
        HumanKnightDark = 8,
        HumanGladiatorA = 9,
        HumanGladiatorB = 10,
        HumanHeavyKnightA = 11,
        HumanHeavyKnightB = 12,
        HumanKnightHood = 13,
        HumanShieldMaiden = 14,
        HumanKnightTemplar = 15,
        HumanKnightTinMan = 16,
        HumanPeasantMan = 17,
        HumanPeasantWoman = 18,
        HumanPrincess = 19,
        HumanWizard = 20,
        HumanExecutioner = 21,
        Elf = 22,
        ElfAssassin = 23,
        ElfFemale = 24,
        ElfKing = 25,
        ElfKnight = 26,
        Goblin = 27,
        GoblinFemale = 28,
        GoblinKing = 29,
        GoblinWarrior = 30,
        GoblinWitchDoctor = 31,
        GoblinHunter = 32,
        UndeadFootmanA = 33,
        UndeadFootmanB = 34,
        UndeadHeavy = 35,
        UndeadKing = 36,
        UndeadRogue = 37,
        UndeadSkeleton = 38
    }
}